on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.100'
        include-prerelease: false
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build Warp.NET.sln -c Release
    - name: Test
      run: dotnet test Warp.NET.sln -c Release --no-build
    - name: Pack
      run: |
        dotnet pack Warp.NET -c Release --no-build -o .
        dotnet pack Warp.NET.SourceGen -c Release --no-build -o .
    - name: Push
      run: dotnet nuget push *.nupkg -s github -k ${NUGET_SECRET} -n --skip-duplicate
      env:
        NUGET_SECRET: ${{ secrets.NUGET_SECRET }}
